name: SonarCloud

on:
  push:
    branches:
      - main  # Substitua "main" pela sua branch principal, se for o caso
  pull_request:
    branches:
      - main

jobs:
  sonarcloud:
    name: Run SonarCloud analysis
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'

    - name: Cache SonarCloud dependencies
      uses: actions/cache@v3
      with:
        path: ~/.sonar/cache
        key: ${{ runner.os }}-sonar-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-sonar-

    - name: SonarCloud Scan
      uses: SonarSource/sonarcloud-github-action@v2
      with:
        organization: tiagoorlamunder
        projectKey: tiagoorlamunder_primefit-api
        projectName: primefit-api
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}  # Token do SonarCloud, configurado como segredo no GitHub
